var tabledata = [
{name: "3DSX Loader",
 url: "https://github.com/0xEBFE/3DSX-IDA-PRO-Loader",
 src: "py",
 cats: "loader",
 last: "20211226",
 desc: "IDA PRO Loader for 3DSX files"},

{name: "abyss",
 url: "https://github.com/patois/abyss",
 src: "py",
 cats: "decomp",
 last: "20220130",
 desc: "Postprocess Hexrays Decompiler Output"},

{name: "ActionScript 3",
 url: "https://github.com/KasperskyLab/ActionScript3",
 src: "py",
 cats: "loader, proc, debug",
 last: "20181005",
 vers: "7.1",
 desc: "An ActionScript 3 processor module and Flash debugger plugin."},

{name: "Adobe Flash disassembler",
 url: "https://hex-rays.com/contests/2009/SWF/ReadMe.txt",
 src: "c++",
 cats: "loader, proc",
 desc: "The 2 plugins present in this archive will enable IDA to parse SWF files, load all SWF tags as segments for fast search and retrieval, parse all tags that can potentially contain ActionScript2 code, discover all such code(a dedicated processor module has been written for it) and even name the event functions acording to event handled in it (eg. OnInitialize). [Download](https://hex-rays.com/contests/2009/SWF/swf.zip)"},

{name: "alleycat",
 url: "https://github.com/devttys0/ida/tree/master/plugins/alleycat",
 src: "py",
 last: "20210602",
 desc: "*  Finds paths to a given code block inside a function\n*  Finds paths between two or more functions\n*  Generates interactive call graphs\n*  Fully scriptable"},

{name: "AlphaGolang",
 url: "https://github.com/SentineLabs/AlphaGolang",
 src: "py",
 last: "20211022",
 vers: "7.6",
 desc: "IDApython Scripts for Analyzing Golang Binaries."},

{name: "AMIE",
 url: "https://github.com/NeatMonster/AMIE",
 src: "py",
 last: "20191027",
 vers: "7.4",
 desc: "A Minimalist Instruction Extender. AMIE is a Python rework of FRIEND that focuses solely on the ARM architecture (only AArch32 and AArch64 are supported). It is both lightweight and dependency-free, and provides the most relevant and up-to-date information about the ARM system registers and instructions."},

{name: "Amnesia",
 url: "https://github.com/duo-labs/idapython",
 src: "py",
 last: "20180426",
 desc: "Amnesia is an IDAPython module designed to use byte level heuristics to find ARM thumb instructions in undefined bytes in an IDA Pro database. Currently, the heuristics in this module find code in a few different ways. Some instructions identify and define new code by looking for comon byte sequences that correspond to particular ARM opcodes. Other functions in this module define new functions based on sequences of defined instructions."},

{name: "Android Debugging",
 url: "https://github.com/techbliss/ADB_Helper_QT_Super_version",
 src: "py",
 cats: "debug",
 last: "20150405",
 desc: "This version have both support for native arm debugging via usb and sdk ADV manager."},

{name: "Android Scripts Collection",
 url: "https://github.com/strazzere/android-scripts",
 src: "py",
 last: "20200503",
 desc: "Collection of Android reverse engineering scripts that make my life easier"},

{name: "APIScout",
 url: "https://github.com/danielplohmann/apiscout",
 src: "py",
 last: "20220117",
 desc: "This project aims at simplifying Windows API import recovery. As input, arbitrary memory dumps for a known environment can be processed (please note: a reference DB has to be built first, using apiscout/db_builder). The output is an ordered list of identified Windows API references with some meta information, and an ApiVector fingerprint. Includes a convenience GUI wrapper for use in IDA."},

{name: "AutoRE",
 url: "https://github.com/a1ext/auto_re",
 src: "py",
 last: "20210804",
 desc: "Auto-renaming plugin with tagging support."},

{name: "Back 2 The Future",
 url: "https://github.com/SafeBreach-Labs/Back2TheFuture",
 src: "py",
 cats: "deobf",
 last: "20210809",
 desc: "Find patterns of vulnerabilities on Windows in order to find 0-day and write exploits of 1-days. We use Microsoft security updates in order to find the patterns."},

{name: "bankswitch",
 url: "https://github.com/patois/bankswitch",
 src: "c++",
 last: "20181218",
 vers: "4.9",
 desc: "Nintendo Entertainment System (NES) bank switcher: plugin for NES ROMs, simulates bank switching/paging."},

{name: "BinAuthor",
 url: "https://github.com/g4hsean/BinAuthor",
 src: "py",
 last: "20200504",
 desc: "Match an author to an unknown binary."},

{name: "BinCAT",
 url: "https://github.com/airbus-seclab/bincat",
 src: "py",
 last: "20211215",
 vers: "7.4",
 desc: "BinCAT is a static Binary Code Analysis Toolkit, designed to help reverse engineers, directly from IDA."},

{name: "BinClone",
 url: "https://github.com/BinSigma/BinClone",
 src: "c++",
 last: "20150404",
 desc: "BinClone: detecting code clones in malware [SERE 2014]"},

{name: "BinDiff",
 url: "http://www.zynamics.com/bindiff.html",
 last: "20210607",
 desc: "BinDiff by Zynamics (now Google) is a comparison tool for binary files, that assists vulnerability researchers and engineers to quickly find differences and similarities in disassembled code."},

{name: "BinExport",
 url: "https://github.com/google/binexport",
 src: "c++",
 cats: "int",
 last: "20220421",
 vers: "7.6",
 desc: "Export disassemblies into Protocol Buffers. BinExport is the exporter component of BinDiff. It is a plugin/extension for IDA that exports disassembly data into the Protocol Buffer format that BinDiff requires."},

{name: "BinNavi",
 url: "https://github.com/google/binnavi",
 cats: "trace",
 last: "20201023",
 desc: "BinNavi is a binary analysis IDE - an environment that allows users to inspect, navigate, edit, and annotate control-flow-graphs of disassembled code, do the same for the callgraph of the executable, collect and combine execution traces, and generally keep track of analysis results among a group of analysts."},

{name: "Bin Sourcerer",
 url: "https://github.com/BinSigma/BinSourcerer",
 src: "py",
 last: "20150204",
 desc: "BinSourcerer (a.k.a RE-Source Online) is an assembly to source code matching framework for binary auditing and malware analysis."},

{name: "Bip",
 url: "https://github.com/synacktiv/bip",
 src: "py",
 last: "20200909",
 desc: "Bip is a project which aims to simplify the usage of python for interacting with IDA. Its main goals are to facilitate the usage of python in the interactive console of IDA and the writing of plugins."},

{name: "Bootroom Analysis Library",
 url: "https://github.com/digitalbond/IBAL",
 src: "py",
 last: "20150212",
 desc: "IBAL is the IDA Pro Bootrom Analysis Library, which contains a number of useful functions for analyzing embedded ROMs."},

{name: "Bosch ME7",
 url: "https://github.com/AndyWhittaker/IDAProBoschMe7x",
 src: "c++",
 last: "20180122",
 desc: "Siemens Bosch ME7.x Disassembler Helper for IDA Pro"},

{name: "BRUTAL IDA",
 url: "https://github.com/tmr232/BRUTAL-IDA",
 src: "py",
 last: "20190801",
 vers: "7.3",
 desc: "Block Redo & Undo To Achieve Legacy IDA."},

{name: "Capa Explorer",
 url: "https://github.com/fireeye/capa/tree/master/capa/ida/plugin",
 src: "py",
 cats: "int",
 last: "20220420",
 vers: "7.7",
 desc: "Capa explorer is an IDAPython plugin that integrates the FLARE team's open-source framework, capa, with IDA Pro. capa is a framework that uses a well-defined collection of rules to identify capabilities in a program."},

{name: "CGEN",
 url: "https://github.com/yifanlu/cgen",
 src: "scm",
 last: "20151228",
 desc: "CGEN with support for generating IDA Pro IDP modules."},

{name: "Class Informer",
 url: "http://sourceforge.net/projects/classinformer/",
 src: "c++",
 last: "20180714",
 vers: "7.1",
 desc: "Scans an MSVC 32bit target IDB for vftables with C++ RTTI, and MFC RTCI type data. Places structure defs, names, labels, and comments to make more sense of class vftables (\"Virtual Function Table\") and make them read easier as an aid to reverse engineering. Creates a list window with found vftables for browsing."},

{name: "Classy",
 url: "https://github.com/RicBent/Classy",
 src: "py",
 last: "20220204",
 desc: "Helps users easily manage classes in IDA Pro. Vtables can be generated by selecting a range, functions can be assigned to classes, their signatures can be easily editing and mangled, IDA structs can be assigned, C headers can be generated, probably more."},

{name: "codatify",
 url: "https://github.com/devttys0/ida/tree/master/plugins/codatify",
 src: "py",
 last: "20210602",
 desc: "\n* Defines ASCII strings that IDA's auto analysis missed\n*  Defines functions/code that IDA's auto analysis missed\n*  Converts all undefined bytes in the data segment into DWORDs (thus allowing IDA to resolve function and jump table pointers)"},

{name: "Codemap",
 url: "https://github.com/c0demap/codemap",
 src: "py",
 cats: "trace",
 last: "20160701",
 vers: "6.6",
 desc: "Codemap is a binary analysis tool for \"run-trace visualization\" provided as IDA plugin."},

{name: "collabREate",
 url: "https://github.com/cseagle/collabREate",
 src: "c++",
 cats: "collab",
 last: "20210901",
 vers: "7.5",
 desc: "collabREate is a plugin for IDA Pro that is designed to provide a collaborative reverse engineering capability for multiple IDA users working on the same binary file."},

{name: "CollaRE",
 url: "https://github.com/Martyx00/CollaRE",
 src: "py",
 cats: "collab",
 last: "20220216",
 desc: "Multi-tool reverse engineering collaboration solution. CollareRE is a tool for collaborative reverse engineering that aims to allow teams that do need to use more then one tool during a project to collaborate without the need to share the files on a separate locations."},

{name: "Comida",
 url: "https://github.com/airbus-cert/comida",
 src: "py",
 cats: "decomp",
 last: "20200513",
 desc: "Comida is a plugin which searches all the references of the GUID COM object (Common Object Model) and deduce the associated type using the Hexrays plugin to improve the readability of the code."},

{name: "Continuum",
 url: "https://github.com/zyantific/continuum",
 src: "py",
 last: "20160913",
 vers: "6.9",
 desc: "Continuum is an IDA Pro plugin adding multi-binary project support, allowing fast navigation in applications involving many shared libraries."},

{name: "Cortex M Firmware",
 url: "https://github.com/duo-labs/idapython",
 src: "py",
 last: "20180426",
 desc: "The Cortex M Firmware module grooms an IDA Pro database containing firmware from an ARM Cortex M microcontroller. This module will annotate the firmware vector table, which contains a number of function pointers. This vector table annotation will cause IDA Pro to perform auto analysis against the functions these pointers point to. "},

{name: "CrowdDetox",
 url: "https://github.com/CrowdStrike/CrowdDetox",
 src: "c++",
 cats: "decomp",
 last: "20210503",
 vers: "6.4",
 desc: "The CrowdDetox plugin for Hex-Rays automatically removes junk code and variables from Hex-Rays function decompilations."},

{name: "CTO: Call Tree Overviewer",
 url: "https://github.com/herosi/CTO",
 src: "py",
 last: "20211224",
 vers: "7.4",
 desc: "IDA plugin for creating a simple and efficient function call tree graph. It can also summarize function information such as internal function calls, API calls, static linked library function calls, unresolved indirect function calls, string references, structure member accesses, specific comments."},

{name: "D-810",
 url: "https://github.com/joydo/d810",
 src: "py",
 cats: "deobf",
 last: "20210225",
 vers: "7.5",
 desc: "D-810 is an IDA Pro plugin which can be used to deobfuscate code at decompilation time by modifying IDA Pro microcode."},

{name: "Dalvik Header",
 url: "https://github.com/strazzere/dalvik-header-plugin",
 src: "c++",
 cats: "decomp",
 last: "20130122",
 desc: "This is a simple Dalvik header plugin for IDA Pro"},

{name: "Data Xref Counter",
 url: "https://github.com/onethawt/idapyscripts",
 src: "py",
 last: "20150917",
 desc: "Enumerates all of the the x-references in a specific segment and counts the frequency of usage. The plugin displays the data in QtTableWidget and lets the user filter and sort the references. You can also export the data to a CSV file."},

{name: "DBGHider",
 url: "https://github.com/iweizime/DBGHider",
 src: "py",
 cats: "debug",
 last: "20180619",
 vers: "7.0",
 desc: "An IDA plugin aims to hide debugger from processes (Windows)."},

{name: "Debugger",
 url: "https://github.com/cseagle/sk3wldbg",
 src: "c++",
 cats: "debug",
 last: "20210726",
 vers: "6.6",
 desc: "Debugger plugin for IDA Pro backed by the Unicorn Engine"},

{name: "deREferencing",
 url: "https://github.com/danigargu/deREferencing",
 src: "py",
 cats: "debug",
 last: "20210505",
 vers: "7.1",
 desc: "IDA Pro plugin that implements more user-friendly register and stack views."},

{name: "Describe Key",
 url: "https://github.com/vmallet/ida-describekey",
 src: "py",
 last: "20220408",
 vers: "7.5",
 desc: "Quickly learn what a shortcut does. Describe Key is a very simple IDA Pro plugin: invoke it, press a shortcut, and instantly see what actions are associated with the shortcut. Quick and easy, call it from anywhere in IDA."},

{name: "Diaphora",
 url: "https://github.com/joxeankoret/diaphora",
 src: "py",
 last: "20211217",
 vers: "7.4",
 desc: "Diaphora (διαφορά, Greek for 'difference') is a program diffing plugin for IDA Pro, similar to Zynamics Bindiff or the FOSS counterparts DarunGrim, TurboDiff, etc... It was released during SyScan 2015."},

{name: "Docker IDA",
 url: "https://github.com/intezer/docker-ida",
 src: "py",
 last: "20171119",
 vers: "6.9",
 desc: "Run IDA Pro disassembler in Docker containers for automating, scaling and distributing the use of IDAPython scripts."},

{name: "dotNIET",
 url: "https://github.com/synacktiv/dotNIET",
 src: "py",
 last: "20210630",
 vers: "7.5",
 desc: "Import missing symbols (usually few thousands) which are resolved at runtime by .NET Native compiled binaries. These symbols lie in SharedLibrary.dll and are not exported by this one."},

{name: "DOXBox Debugger",
 url: "https://github.com/wjp/idados",
 src: "c++",
 cats: "debug",
 last: "20160228",
 vers: "6.9",
 desc: "Eric Fry's IDA/DOSBox debugger plugin"},

{name: "dp701",
 url: "https://github.com/pr701/dp701",
 cats: "ui",
 last: "20210922",
 vers: "7.3",
 desc: "Dark theme for IDA Pro."},

{name: "DrGadget",
 url: "https://github.com/patois/DrGadget",
 src: "py",
 last: "20170202",
 desc: "This is an IDAPython plugin for the Interactive Disassembler for all your ROP experimentation needs."},

{name: "DriverBuddy",
 url: "https://github.com/nccgroup/DriverBuddy",
 src: "py",
 last: "20181122",
 desc: "DriverBuddy is an IDA Python script to assist with the reverse engineering of Windows kernel drivers."},

{name: "Drop",
 url: "https://github.com/Riscure/DROP-IDA-plugin",
 src: "py",
 last: "20171222",
 vers: "6.95",
 desc: "An experimental IDA Pro plugin capable of detecting several types of opaque predicates in obfuscated binaries. It leverages the power of the symbolic execution engine angr and its components to reason about the opaqueness of predicates based on their symbolic context."},

{name: "dsync",
 url: "https://github.com/patois/dsync",
 src: "py",
 cats: "decomp",
 last: "20210120",
 vers: "7.3",
 desc: "IDAPython plugin that synchronizes decompiled and disassembled code views."},

{name: "dumpDyn",
 url: "https://github.com/secrary/IDA-scripts/tree/master/dumpDyn",
 src: "py",
 last: "20190226",
 desc: "Script which saves comments, names, breakpoints, functions from one execution to another, f a process allocates a dynamic memory using VirtualAlloc, HeapAlloc, new, etc. and continues execution from that address."},

{name: "dwarfexport",
 url: "https://github.com/ALSchwalm/dwarfexport",
 src: "c++",
 last: "20201118",
 vers: "7.2",
 desc: "dwarfexport is an IDA Pro plugin that allows the user to export dwarf debug information. This can then be imported in to gdb and other tools, allowing you to debug using info you have recovered in IDA even when you cannot connect the IDA debugger."},

{name: "DWARF Plugin",
 url: "https://github.com/vrasneur/idadwarf",
 src: "c++",
 last: "20091115",
 vers: "5.5",
 desc: "IDADWARF is an IDA plugin that imports DWARF debugging symbols into an IDA database. [Download](https://hex-rays.com/contests/2009/IDADwarf-0.2/idadwarf-0.2.zip)"},

{name: "Dynamic Data Resolver",
 url: "https://github.com/Cisco-Talos/DynDataResolver",
 src: "py",
 cats: "trace",
 last: "20201217",
 vers: "7.5",
 desc: "A plugin for IDA that aims to make the reverse-engineering of malware easier. Features: Code Flow Trace, Searchable API call logging, Searchable string logging, Resolving dynamic values and auto-commenting."},

{name: "Dynamic IDA Enrichment",
 url: "https://github.com/ynvb/DIE",
 src: "py",
 cats: "debug, trace",
 last: "20210513",
 vers: "7.2",
 desc: "DIE is an IDA python plugin designed to enrich IDA`s static analysis with dynamic data. This is done using the IDA Debugger API, by placing breakpoints in key locations and saving the current system context once those breakpoints are hit."},

{name: "Dynlib",
 url: "https://github.com/aerosoul94/dynlib",
 src: "c++",
 last: "20171216",
 vers: "7.0",
 desc: "This is an IDA Pro plugin to aid in reverse engineering PS4 user mode elf's by loading the PS4 specific DYNLIBDATA segment."},

{name: "EFI Scripts",
 url: "https://github.com/danse-macabre/ida-efitools",
 src: "py",
 last: "20150713",
 desc: "Some IDA scripts and tools to assist with reverse engineering EFI executables."},

{name: "efiXplorer",
 url: "https://github.com/binarly-io/efiXplorer",
 src: "c++",
 last: "20220421",
 vers: "7.7",
 desc: "IDA plugin for UEFI firmware analysis and reverse engineering automation."},

{name: "epanos",
 url: "https://github.com/drvink/epanos",
 src: "py",
 cats: "decomp",
 last: "20140505",
 vers: "6.6",
 desc: "ElectroPaint Automatic No-source Object reaSsembler (a MIPS to C decompiler). This is a very dumb MIPS to C static translator."},

{name: "EtherAnnotate",
 url: "https://github.com/inositle/etherannotate_ida",
 src: "c++",
 cats: "trace",
 last: "20100504",
 desc: "Parses the specialized instruction trace files that are generated using the EtherAnnotate Xen modification (http://github.com/inositle/etherannotate_xen).  From the instruction trace, register values and code coverage of the run-time information are visualized in IDA Pro through instruction comments and line colorations."},

{name: "Extract Macho-O",
 url: "https://github.com/gdbinit/ExtractMachO",
 src: "c++",
 last: "20190509",
 vers: "6.3",
 desc: "This is a very simple IDA plugin to extract all Mach-O binaries contained anywhere in the disassembly."},

{name: "FCatalog",
 url: "https://github.com/xorpd/fcatalog_client",
 src: "py",
 last: "20160819",
 desc: "FCatalog (The functions catalog) is a mechanism for finding similarities between different binary blobs in an efficient manner. It is mostly useful for identifying a new binary blob is somewhat similar to a binary blob that have been encountered before. The client side of FCatalog is an IDA plugin that allows a group of reverse engineers to manage a pool of reversed functions. Whenever a new binary function is encountered, FCatalog can compare it to all the known and previously reversed binary functions."},

{name: "Findcrypt-yara",
 url: "https://github.com/polymorf/findcrypt-yara",
 src: "py",
 last: "20220105",
 vers: "7.4",
 desc: "IDA pro plugin to find crypto constants (and more)"},

{name: "FindYara",
 url: "https://github.com/OALabs/findyara-ida",
 src: "py",
 last: "20211228",
 vers: "7.0",
 desc: "IDA python plugin to scan binary with Yara rules."},

{name: "FIRST",
 url: "https://github.com/Cisco-Talos/FIRST-plugin-ida",
 src: "py",
 last: "20200131",
 vers: "7.3",
 desc: "Function Identification and Recovery Signature Tool (FIRST) is a plugin for IDA Pro that allows users to automatically search for and apply function metadata (the function name, parameter names, parameter types, comments, etc.) submitted from different IDBs / users. This functionality is similar to IDA's Lumina feature, which was introduced in IDA 7.2, although with FIRST the function metadata server address is configurable and the FIRST server code is open source, which means the user can set up a private metadata server for internal use if desired. A community database is also maintained by Cisco Talos and available to use free-of-charge. FIRST supports IDA 6.9 SP1 and above."},

{name: "flare-emu",
 url: "https://github.com/fireeye/flare-emu",
 src: "py",
 last: "20210419",
 desc: "flare-emu marries a supported binary analysis framework, such as IDA Pro or Radare2, with Unicorn’s emulation framework to provide the user with an easy to use and flexible interface for scripting emulation tasks. It is designed to handle all the housekeeping of setting up a flexible and robust emulator for its supported architectures so that you can focus on solving your code analysis problems. Currently, flare-emu supports the x86, x86_64, ARM, and ARM64 architectures."},

{name: "FLARE IDA Decompiler Library (FIDL)",
 url: "https://github.com/fireeye/FIDL",
 src: "py",
 last: "20220208",
 vers: "7.4",
 desc: "A sane API for IDA Pro's decompiler."},

{name: "FLARE Plugins",
 url: "https://github.com/fireeye/flare-ida",
 last: "20211214",
 desc: "Shellcode Hashes, Struct Typer, StackStrings, MSDN Annotations, ApplyCalleType"},

{name: "FLIRTDB",
 url: "https://github.com/Maktm/FLIRTDB",
 cats: "int",
 last: "20200523",
 desc: "A community driven collection of IDA FLIRT signature files."},

{name: "FLS Loader",
 url: "https://github.com/rpw/flsloader",
 src: "py",
 cats: "loader",
 last: "20120419",
 vers: "6.2",
 desc: "IDA Pro loader module for IFX iPhone baseband firmwares. Based on a universal scatter loader script by roxfan."},

{name: "Fluorescence",
 url: "https://github.com/devttys0/ida/tree/master/plugins/fluorescence",
 src: "py",
 last: "20210602",
 vers: "7.4",
 desc: "Un/highlights function call instructions"},

{name: "FRAPL",
 url: "https://github.com/FriedAppleTeam/FRAPL",
 src: "py",
 cats: "int",
 last: "20161226",
 vers: "6.95",
 desc: "FRAPL is a reverse engineering framework created to simplify dynamic instrumentation with Frida."},

{name: "Free the debuggers",
 url: "https://github.com/techbliss/Free_the_Debuggers",
 src: "py",
 cats: "debug",
 last: "20150207",
 vers: "6.7",
 desc: "Free the ida pro debuggers for all files."},

{name: "Frida",
 url: "https://github.com/techbliss/Frida_For_Ida_Pro",
 src: "py",
 cats: "int",
 last: "20150405",
 vers: "6.7",
 desc: "This is plugin for ida pro thar uses the Frida api. Mainly trace functions."},

{name: "FRIEND",
 url: "https://github.com/alexhude/FRIEND",
 src: "c++",
 last: "20210726",
 vers: "7.0",
 desc: "Flexible Register/Instruction Extender aNd Documentation. FRIEND is an IDA plugin created to improve disassembly and bring register/instruction documentation right into IDA View. (see also: AMIE)"},

{name: "Funcap",
 url: "https://github.com/deresz/funcap",
 src: "py",
 cats: "trace",
 last: "20160304",
 vers: "6.6",
 desc: "This script records function calls (and returns) across an executable using IDA debugger API, along with all the arguments passed. It dumps the info to a text file, and also inserts it into IDA's inline comments. This way, static analysis that usually follows the behavioral runtime analysis when analyzing malware, can be directly fed with runtime info such as decrypted strings returned in function's arguments."},

{name: "FuncScanner",
 url: "https://github.com/patois/FuncScanner",
 src: "py",
 last: "20201206",
 vers: "7.3",
 desc: "Collects extended function properties from IDA Pro databases. This is especially useful in reverse engineering code that comes with no or little symbolic information, as is often the case with embedded firmware."},

{name: "Functions+",
 url: "https://github.com/nihilus/functions-plus",
 src: "py",
 last: "20181225",
 vers: "7.5",
 desc: "IDA Pro plugin to make functions tree view. Plugin parses function names and groups them by namespaces."},

{name: "Function Tagger",
 url: "https://github.com/alessandrogario/IDA-Function-Tagger",
 src: "py",
 last: "20210526",
 vers: "7.6",
 desc: "This IDAPython script tags subroutines according to their use of imported functions"},

{name: "Gamecube DSP",
 url: "https://github.com/dolphin-emu/gcdsp-ida",
 src: "py",
 cats: "proc",
 last: "20141213",
 vers: "6.9",
 desc: "This project adds support for the DSP present in the Gamecube and the Wii to IDA, the Interactive Disassembler [1]. This allows easy analyze of a DSP ucode, handling cross-references, control flow, and so on."},

{name: "Gamecube Extension",
 url: "https://github.com/hyperiris/gekkoPS",
 src: "c++",
 last: "20180425",
 vers: "5.2",
 desc: "This is a Gekko CPU Paired Single extension instructions plug-in for IDA Pro 5.2"},

{name: "garmin-ida-loader",
 url: "https://sourceforge.net/projects/garminidaloader/",
 src: "c++",
 cats: "loader",
 last: "20130530",
 desc: "IDA loader for Garmin firmwares."},

{name: "gdbida",
 url: "https://github.com/comsecuris/gdbida",
 last: "20180423",
 desc: "A visual bridge between a GDB session and IDA Pro's disassembler"},

{name: "genmc",
 url: "https://github.com/patois/genmc",
 src: "py",
 cats: "dev",
 last: "20210115",
 vers: "7.3",
 desc: "Genmc is an IDAPython script/plugin hybrid that displays Hexrays decompiler microcode, which can help in developing microcode plugins."},

{name: "Geolocator",
 url: "https://github.com/techbliss/ida_pro_http_ip_geolocator",
 src: "py",
 cats: "int",
 last: "20190310",
 vers: "7.0",
 desc: "Lookup (geolocate) IP's and http/https addresses, using google maps, and MaxMind databases."},

{name: "GhIDA",
 url: "https://github.com/Cisco-Talos/GhIDA",
 src: "py",
 cats: "decomp, int",
 last: "20201216",
 vers: "7.4",
 desc: "GhIDA is an IDA Pro plugin that integrates the Ghidra decompiler in IDA."},

{name: "golang_loader_assist",
 url: "https://github.com/strazzere/golang_loader_assist",
 src: "py",
 last: "20200622",
 vers: "7.5",
 desc: "Making GO reversing easier in IDA Pro."},

{name: "go_parser",
 url: "https://github.com/0xjiayu/go_parser",
 src: "py",
 last: "20210729",
 desc: "Yet Another Golang binary parser for IDAPro. Inspired by golang_loader_assist and jeb-golang-analyzer, I wrote a more complete Go binaries parsing tool for IDAPro."},

{name: "grap",
 url: "https://github.com/QuoSecGmbH/grap",
 src: "py",
 last: "20220316",
 vers: "7.1",
 desc: "Define and match graph patterns within binaries. grap takes patterns and binary files, uses a Casptone-based disassembler to obtain the control flow graphs from the binaries, then matches the patterns against them."},

{name: "GraphGrabber",
 url: "https://github.com/tmr232/GraphGrabber",
 src: "py",
 last: "20171120",
 vers: "7.0",
 desc: "Grab full-resolution images of IDA graphs."},

{name: "Graph Slick",
 url: "https://github.com/lallousx86/GraphSlick",
 src: "c++",
 last: "20141120",
 desc: "Automated detection of inlined functions. It highlights similar groups of nodes and allows you to group them, simplifying complex functions. The authors provide an accompanying presentation which explains the algorithms behind the plugin and shows sample use cases."},

{name: "HeapViewer",
 url: "https://github.com/danigargu/heap-viewer",
 src: "py",
 last: "20210713",
 vers: "7.4",
 desc: "An IDA Pro plugin to examine the heap, focused on exploit development."},

{name: "Hex-Rays Block Highlighter",
 url: "https://github.com/vmallet/ida-hex-highlighter",
 src: "py",
 cats: "decomp, ui",
 last: "20220417",
 vers: "7.5",
 desc: "Highlight code blocks in the Hex-Rays decompiler output. In some cases the decompilation output can be quite hairy with lots of nested blocks and it can be hard to follow where one ends and the other begins. This plugin will highlight blocks in a sticky way, allowing one to navigate within the window while keeping the block highlight around."},

{name: "HexRays CodeXplorer",
 url: "https://github.com/REhints/HexRaysCodeXplorer",
 src: "c++",
 cats: "decomp",
 last: "20220309",
 vers: "7.7",
 desc: "The Hex-Rays Decompiler plugin for better code navigation in RE process. CodeXplorer automates code REconstruction of C++ applications or modern malware like Stuxnet, Flame, Equation, Animal Farm ..."},

{name: "HexRaysDeob",
 url: "https://github.com/RolfRolles/HexRaysDeob",
 src: "c++",
 cats: "deobf",
 last: "20190827",
 vers: "7.3",
 desc: "A Hex-Rays microcode API plugin breaking an obfuscating compiler used to create an in-the-wild malware family. The plugin is fully automatic and requires no user intervention; upon installation, the decompilation listings presented to the user will be free of obfuscation."},

{name: "HexRaysPyTools",
 url: "https://github.com/igogo-x86/HexRaysPyTools",
 src: "py",
 cats: "decomp",
 last: "20200215",
 vers: "7.4",
 desc: "Plugin assists in creation classes/structures and detection virtual tables. Best to use with Class Informer plugin, because it helps to automatically get original classes names."},

{name: "hexrays_scripts",
 url: "https://github.com/patois/hexrays_scripts",
 src: "py",
 last: "20220407",
 desc: "Various scripts for the Hexrays decompiler (kloppy, shuffle, arachno, IDA coffee, screenrecorder, ricky)."},

{name: "Hexrays Toolbox",
 url: "https://github.com/patois/HexraysToolbox",
 src: "py",
 cats: "decomp",
 last: "20211105",
 vers: "7.4",
 desc: "Find code patterns within the Hexrays AST"},

{name: "HexRays Tools",
 url: "https://github.com/nihilus/hexrays_tools",
 src: "py",
 cats: "decomp, dev",
 last: "20160126",
 vers: "7.4",
 desc: "* Assist in creation of new structure definitions / virtual calls detection\n* Jump directly to virtual function or structure member definition\n* Gives list of structures with given size, with given offset\n* Finds structures with same \"shape\" as is used.\n* convert function to __usercall or __userpurge\n* and more...."},

{name: "HRDEV",
 url: "https://github.com/ax330d/hrdev",
 src: "py",
 cats: "decomp",
 last: "20180921",
 vers: "6.6",
 desc: "This is an IDA Pro Python plugin to make Hex-Rays Decompiler output bit more attractive. HRDEV plugin retrieves standard decompiler output, parses it with Python Clang bindings, does some magic, and puts back."},

{name: "HrDevHelper",
 url: "https://github.com/patois/HRDevHelper",
 src: "py",
 cats: "decomp, dev",
 last: "20211104",
 vers: "7.3",
 desc: "HexRays decompiler plugin that visualizes the ctree of decompiled functions using IDA's graph engine."},

{name: "Hyara",
 url: "https://github.com/hyuunnn/Hyara",
 src: "py",
 last: "20211101",
 desc: "A plugin to create pattern-matching rules. It helps creating rules for the YARA pattern-matching tool direcly in IDA. It includes a simple detection of relocatable bytes in x86 opcodes for improved matching. It also provides a checker feature for testing the rules on the loaded binary."},

{name: "IDA2SQL",
 url: "https://github.com/zynamics/ida2sql-plugin-ida",
 src: "py",
 cats: "int",
 last: "20120110",
 vers: "5.7",
 desc: "As the name implies this plugin can be used to export information from IDA databases to SQL databases. This allows for further analysis of the collected data: statistical analysis, building graphs, finding similarities between programs, etc."},

{name: "IDA 7.x VS2017 Sample Project",
 url: "https://github.com/patois/ida_vs2017",
 src: "c++",
 cats: "dev",
 last: "20180510",
 vers: "7.0",
 desc: "This is a sample Visual Studio 2017 (Community Edition) project for IDA 7.x plugins on Windows."},

{name: "ida-arm-system-highlight",
 url: "https://github.com/gdelugre/ida-arm-system-highlight",
 src: "py",
 last: "20210928",
 vers: "7.4",
 desc: "This script will give you the list of ARM system instructions used in your IDA database. This is useful for locating specific low-level pieces of code (setting up the MMU, caches, fault handlers, etc.)."},

{name: "IDA Autoruns",
 url: "https://github.com/tmr232/ida-autoruns",
 src: "py",
 last: "20160221",
 vers: "6.8",
 desc: "IDA-Autoruns is a simple plugin to make a script run automatically every time you open a specific IDB."},

{name: "IDA Batch Decompile",
 url: "https://github.com/tintinweb/ida-batch_decompile",
 src: "py",
 cats: "decomp",
 last: "20180712",
 vers: "7.0",
 desc: "Batch decompile multiple files and their imports with additional annotations (xref, stack var size) to a pseudocode .c file."},

{name: "ida bitfields",
 url: "https://github.com/JustasMasiulis/ida_bitfields",
 src: "c++",
 cats: "decomp",
 last: "20220401",
 desc: "A simple IDA Pro plugin to make bitfields and bitflags in them easier to reason about."},

{name: "IDA BPF Processor",
 url: "https://github.com/bnbdr/ida-bpf-processor",
 src: "py",
 last: "20180827",
 vers: "7.0",
 desc: "BPF Bytecode Processor for IDA (python). Supports the old BPF bytecode only (no eBPF)."},

{name: "IDABuddy",
 url: "https://github.com/tmr232/IDABuddy",
 src: "py",
 last: "20170917",
 vers: "6.9",
 desc: "IDABuddy is a reverse-engineer's best friend. Designed to be everything Clippy the Office Assistant was, and more!"},

{name: "IDA C#",
 url: "https://blog.karatos.in/a?ID=01000-69f2f124-560e-47a5-bb0c-93052d9763af",
 cats: "dev",
 last: "20100605",
 desc: "Scripting IDA with C#, download [here](https://files.cnblogs.com/nnhy/IDACSharp_20100605143116.rar). (All in Chinese)."},

{name: "ida-climacros",
 url: "https://github.com/0xeb/ida-climacros",
 src: "c++",
 last: "20210105",
 vers: "7.5",
 desc: "`ida-climacros` is a productivity plugin that allows you to define macros that will be expanded when interfacing with IDA's command line interpreter (in the output window)."},

{name: "ida-cmake",
 url: "https://github.com/0xeb/ida-cmake",
 cats: "dev",
 last: "20220223",
 vers: "7.6",
 desc: "This is not an IDA plugin but a CMake project generator for IDA plugins development."},

{name: "ida-cmake",
 url: "https://github.com/zyantific/ida-cmake",
 cats: "dev",
 last: "20170902",
 vers: "7.0",
 desc: "CMake build scripts and a Python helper allowing compilation of C++ IDA plugins for Windows, macOS and Linux without much user effort."},

{name: "IDA Color Schemer",
 url: "https://github.com/tmr232/IDAColorSchemer",
 src: "py",
 cats: "ui",
 last: "20190105",
 vers: "7.2",
 desc: "tool to easily design IDA color schemes outside IDA. This will hopefully allow simplifying & automating the generation of color schemes and help create colorblind-friendly settings."},

{name: "IDA Compare",
 url: "https://github.com/dzzie/IDACompare",
 src: "c++",
 last: "20190530",
 vers: "6.7",
 desc: "IDA disassembly level diffing tool, find patches and modifications between malware variants. See mydoom A/B sample database and video trainer for usage."},

{name: "IDACyber",
 url: "https://github.com/patois/IDACyber",
 src: "py",
 last: "20211217",
 vers: "7.4",
 desc: "IDACyber is a plugin that visualizes an IDA database's content."},

{name: "idadiff",
 url: "https://github.com/0x00ach/idadiff",
 src: "py",
 last: "20170517",
 desc: "IDAPython script to auto-rename subs using the MACHOC algorithm."},

{name: "IDA EA",
 url: "https://github.com/1111joe1111/ida_ea",
 src: "py",
 last: "20171128",
 vers: "7.0",
 desc: "A set of exploitation/reversing aids for IDA. Provides a context viewer, instruction emulator, heap explorer, trace dumper, GDB integration, Styling"},

{name: "idaemu",
 url: "https://github.com/36hours/idaemu",
 src: "py",
 last: "20161215",
 vers: "6.9",
 desc: "Emulate code in IDA Pro. it is based on unicorn-engine."},

{name: "IDA-EVM",
 url: "https://github.com/crytic/ida-evm",
 src: "py",
 cats: "proc",
 last: "20180411",
 vers: "7.0",
 desc: "IDA Processor Module for the Ethereum Virtual Machine (EVM)."},

{name: "IDA Extrapass",
 url: "http://sourceforge.net/projects/idaextrapassplugin/",
 src: "c++",
 last: "20180713",
 vers: "7.1",
 desc: "An IDA Pro Win32 target clean up plug-in by Sirmabus. It does essentially four cleaning/fixing steps: Convert stray code section values to \"unknown\", fix missing \"align\" blocks, fix missing code bytes, and locate and fix missing/undefined functions."},

{name: "IDA Eye",
 url: "http://www.mfmokbel.com/Down/RCE/Documentation.html",
 src: "c++",
 last: "20180310",
 vers: "7.0",
 desc: "Plugin that enables you to perform different operations at the mnemonic level, independent of any particular processor type. These operations are facilitated through a parameterized template, which include the capabilities to de/highlight instructions, gather statistical information about the frequency of each instruction, and search for sequences of mnemonics, among other features."},

{name: "IDA-For-Delphi",
 url: "https://github.com/Coldzer0/IDA-For-Delphi",
 src: "py",
 last: "20190920",
 desc: "IDA Python Script to Get All function names from Event Constructor (VCL)."},

{name: "IDAFuzzy",
 url: "https://github.com/Ga-ryo/IDAFuzzy",
 src: "py",
 last: "20191216",
 vers: "7.4",
 desc: "IDAFuzzy is fuzzy searching tool for IDA Pro. This tool helps you to find command/function/struct and so on. (a la Mac Spotlight)."},

{name: "ida_game_elf_loaders (gel)",
 url: "https://github.com/aerosoul94/ida_gel",
 src: "c++",
 cats: "loader",
 last: "20191003",
 vers: "6.8",
 desc: "A collection of IDA loaders for various game console ELF's: PS3, PSVita, WiiU."},

{name: "ida-genesis",
 url: "https://github.com/zznop/ida-genesis",
 src: "py",
 cats: "loader",
 last: "20200216",
 desc: "Suite of IDA scripts for SEGA Genesis ROM hacking. ROM Loader, Branch Table Enumeration."},

{name: "idahunt",
 url: "https://github.com/nccgroup/idahunt",
 src: "py",
 last: "20220104",
 desc: "idahunt is a framework to analyze binaries with IDA Pro and hunt for things in IDA Pro. It is command line tool to analyse all executable files recursively from a given folder. It executes IDA in the background so you don't have to open manually each file. It supports executing external IDA Python scripts."},

{name: "IDA iBoot Loader",
 url: "https://github.com/matteyeux/ida-iboot-loader",
 src: "py",
 cats: "loader",
 last: "20211219",
 desc: "IDA loader for Apple's 64 bits iBoot, SecureROM and AVPBooter."},

{name: "idaidle",
 url: "https://github.com/google/idaidle",
 src: "c++",
 last: "20210217",
 vers: "7.5",
 desc: "idaidle is a plugin for the commercial IDA Pro disassembler that warns users if they leave their instance idling for too long. After a predetermined amount of idle time, the plugin first warns and later then saves the current disassemlby database and closes IDA."},

{name: "IDA Images",
 url: "https://github.com/rr-/ida-images",
 src: "py",
 last: "20201107",
 vers: "7.0",
 desc: "Image preview plugin for IDA disassembler."},

{name: "IDA IPython",
 url: "https://github.com/james91b/ida_ipython",
 src: "c++",
 cats: "dev, int",
 last: "20170805",
 vers: "6.9",
 desc: "This is a plugin to embed an IPython kernel in IDA Pro. The Python ecosystem has amazing libraries (and communities) for scientific computing. IPython itself is great for exploratory data analysis. Using tools such as the IPython notebook make it easy to share code and explanations with rich media. IPython makes using IDAPython and interacting with IDA programmatically really fun and easy."},

{name: "IDA Key Checker",
 url: "https://github.com/pr701/ida_key_checker",
 src: "c++",
 last: "20210922",
 vers: "7.0",
 desc: "IDA Pro key checker tool, check IDA keys from the command line."},

{name: "IDAMagicStrings",
 url: "https://github.com/joxeankoret/idamagicstrings",
 src: "py",
 last: "20191108",
 vers: "7.4",
 desc: "An IDA Python plugin to extract information from string constants. The current version of the plugin is able to:\n* Display functions to source files relationships (in a tree and in a plain list, a chooser in IDA language).\n* Display guessed function names for functions.\n* Rename functions according to the source code file their belong + address (for example, memory_mgmt_0x401050).\n* Rename functions according to the guessed function name."},

{name: "idamagnum",
 url: "https://github.com/lucasg/idamagnum",
 src: "py",
 cats: "int",
 last: "20200410",
 vers: "7.4",
 desc: "A plugin for integrating MagnumDB requests within IDA. MagNumDB is a database that contains about 380,000 items. These items are constants, names, values all extracted from more than 6,000 header files (.h, .hxx, .hpp, .idl, etc.) provided by standard Windows and Visual Studio SDKs and WDKs. "},

{name: "ida_medigate",
 url: "https://github.com/medigate-io/ida_medigate",
 src: "py",
 cats: "decomp",
 last: "20210215",
 vers: "7.5",
 desc: "Medigate plugin for c++ reverse engineering and other utils. Two parts:\n* Implementation of C++ classes and polymorphism over IDA\n* A RTTI parser which rebuilds the classes hierarchy."},

{name: "IDA Migrator",
 url: "https://github.com/giladreich/ida_migrator",
 src: "py",
 last: "20210528",
 vers: "7.6",
 desc: "IDA Migrator plugin makes the job of migrating symbols and type informations from one IDA database instance to another. It will help migrating function names, structures and enums. This comes in handy when:\n* Moving to a newer version of IDA that does better analysis and you don't want to change in the new instance type information or variable names of the decompiled functions.\n* The current idb instance fails to decompile a function or the decompilation looks wrong in comparison to another idb instance of the same binary.\n* Experimenting on another idb instance before making major changes on the current instance.\n* A lightweight easy way of creating small backups of the current work.\n* For w/e reason, the current idb instance you're working on gets corrupted."},

{name: "IDA-minsc",
 url: "https://github.com/arizvisa/ida-minsc",
 src: "py",
 cats: "dev",
 last: "20220414",
 vers: "7.4",
 desc: "A plugin that assists a user with scripting the IDAPython plugin that is bundled with the disassembler. This plugin groups the different aspects of the IDAPython API into a simpler format which allows a reverse engineer to script different aspects of their work with very little investment."},

{name: "IDAngr",
 url: "https://github.com/andreafioraldi/IDAngr",
 src: "py",
 cats: "debug, int",
 last: "20200722",
 desc: "Use angr in the ida debugger generating a state from the current debug session."},

{name: "IDA - Nightfall",
 url: "https://github.com/0xItx/ida_nightfall",
 src: "py",
 cats: "ui",
 last: "20190625",
 vers: "7.3",
 desc: "A dark color theme for IDA Pro"},

{name: "IDAObjcTypes",
 url: "https://github.com/PoomSmart/IDAObjcTypes",
 src: "py",
 last: "20220329",
 vers: "7.2",
 desc: "A collection of (public and private) types and functions definitions useful for Objective-C binaries analysis."},

{name: "IDA Patcher",
 url: "https://github.com/iphelix/ida-patcher",
 src: "py",
 last: "20140923",
 desc: "IDA Patcher is a plugin for Hex-Ray's IDA Pro disassembler designed to enhance IDA's ability to patch binary files and memory."},

{name: "IDA Patchwork",
 url: "https://bitbucket.org/daniel_plohmann/idapatchwork",
 src: "py",
 last: "20141104",
 desc: "Stitching against malware families with IDA Pro (tool for the talk at Spring9, https://spring2014.gdata.de/spring2014/programm.html). In essence, I use a somewhat fixed / refurbished version of PyEmu along IDA to demonstrate deobfuscation of the different patterns found in the malware family Nymaim."},

{name: "IDA Plugin Loader",
 url: "https://github.com/tmr232/ida-plugin-loader",
 src: "py",
 last: "20191027",
 vers: "7.4",
 desc: "Random IDA scripts, plugins, example code (some of it may be old and not working anymore)."},

{name: "idaplugins",
 url: "https://github.com/patois/idaplugins",
 src: "c++",
 last: "20170205",
 desc: "Random IDA scripts, plugins, example code (some of it may be old and not working anymore)."},

{name: "idaplugins",
 url: "https://github.com/tmr232/ida-plugins",
 src: "py",
 last: "20150531",
 vers: "6.7",
 desc: "Plugins for IDA: Plugin Proxy, Function Strings, LCA Graph, Autoenum, Autostruct, Function Flow, Quick Copy."},

{name: "idapm",
 url: "https://github.com/tkmru/idapm",
 src: "py",
 last: "20200905",
 desc: "idapm is IDA Plugin Manager. It works perfectly on macOS, it probably works on Windows and Linux."},

{name: "IDAPyHelper",
 url: "https://github.com/patois/IDAPyHelper",
 src: "py",
 cats: "dev",
 last: "20191123",
 vers: "7.0",
 desc: "IDAPyHelper is a script for the Interactive Disassembler that helps writing IDAPython scripts and plugins."},

{name: "IDA Python Embedded Toolkit",
 url: "https://github.com/maddiestone/IDAPythonEmbeddedToolkit",
 last: "20190814",
 desc: "IDAPython scripts for automating analysis of firmware of embedded devices."},

{name: "IDARay",
 url: "https://github.com/SouhailHammou/IDARay-Plugin",
 last: "20181116",
 desc: "IDARay is an IDA Pro plugin that matches the database against multiple YARA files. Maybe your rules are scattered over multiple YARA files or you simply want to match against as much rules as possible, IDARay is here to help."},

{name: "IDA Ref",
 url: "https://github.com/nologic/idaref",
 last: "20211020",
 desc: "IDA Pro Full Instruction Reference Plugin - It's like auto-comments but useful."},

{name: "IDA Rest",
 url: "https://github.com/dshikashio/idarest",
 last: "20150321",
 desc: "A simple REST-like API for basic interoperability with IDA Pro."},

{name: "IDArling",
 url: "https://github.com/IDArlingTeam/IDArling/",
 src: "py",
 cats: "collab",
 last: "20210217",
 vers: "7.0",
 desc: "IDArling is a collaborative reverse engineering plugin for IDA Pro and Hex-Rays. It allows to synchronize in real-time the changes made to a database by multiple users, by connecting together different instances of IDA Pro."},

{name: "IDArling (Fork)",
 url: "https://github.com/fidgetingbits/IDArling",
 src: "py",
 cats: "collab",
 last: "20220110",
 vers: "7.5",
 desc: "IDArling is a collaborative reverse engineering plugin for IDA Pro and Hex-Rays. This is an actively maintained fork of the now-abandoned IDARling above."},

{name: "IDA Scope",
 url: "https://github.com/danielplohmann/idascope",
 last: "20200813",
 desc: "IDAscope is an IDA Pro extension with the goal to ease the task of (malware) reverse engineering with a current focus on x86 Windows. It consists of multiple tabs, containing functionality to achieve different goals such as fast identification of semantically interesting locations in the analysis target, seamless access to MSDN documentation of Windows API, and finding of potential crypto/compression algorithms."},

{name: "IDAShell",
 url: "https://github.com/namazso/IDAShell",
 src: "c++",
 cats: "int",
 last: "20210729",
 desc: "IDAShell is a shell extension for launching IDA from the context menu of executables (Windows)."},

{name: "IDA Signature Matching Tool",
 url: "http://sourceforge.net/projects/idasignsrch/",
 src: "c++",
 last: "20180713",
 vers: "7.1",
 desc: "Tool for searching signatures inside files, extremely useful as help in reversing jobs like figuring or having an initial idea of what encryption/compression algorithm is used for a proprietary protocol or file. It can recognize tons of compression, multimedia and encryption algorithms and\nmany other things like known strings and anti-debugging code which can be also manually added since it's all based on a text signature file read at run-time and easy to modify."},

{name: "IDA Skins",
 url: "https://github.com/zyantific/IDASkins",
 src: "py",
 cats: "ui",
 last: "20190615",
 vers: "7.2",
 desc: "Plugin providing advanced skinning support for the Qt version of IDA Pro utilizing Qt stylesheets, similar to CSS."},

{name: "IDA Sploiter",
 url: "https://github.com/iphelix/ida-sploiter",
 src: "py",
 last: "20190513",
 vers: "6.5",
 desc: "IDA Sploiter is a plugin for Hex-Ray's IDA Pro disassembler designed to enhance IDA's capabilities as an exploit development and vulnerability research tool. Some of the plugin's features include a powerful ROP gadgets search engine, semantic gadget analysis and filtering, interactive ROP chain builder, stack pivot analysis, writable function pointer search, cyclic memory pattern generation and offset analysis, detection of bad characters and memory holes, and many others."},

{name: "IDA Stealth",
 url: "https://github.com/nihilus/idastealth",
 src: "c++",
 cats: "debug",
 last: "20140914",
 vers: "5.6",
 desc: "IDAStealth is a plugin which aims to hide the IDA debugger from most common anti-debugging techniques. The plugin is composed of two files, the plugin itself and a dll which is injected into the debuggee as soon as the debugger attaches to the process. The injected dll actually implements most of the stealth techniques either by hooking system calls or by patching some flags in the remote process."},

{name: "IDA StrikeOut",
 url: "https://github.com/0xeb/ida-strikeout",
 src: "c++",
 cats: "decomp",
 last: "20211227",
 vers: "7.5",
 desc: "IDA strike-out: A Hex-Rays decompiler plugin to patch the Ctree (e.g. remove statements)."},

{name: "IDA StringCluster",
 url: "https://github.com/Comsecuris/ida_strcluster",
 src: "py",
 last: "20180314",
 vers: "6.9",
 desc: "This plugin extends IDA Pro's capabilities to display strings within the binary by clustering found strings on a per-function basis."},

{name: "IDA Toolbag",
 url: "https://github.com/aaronportnoy/toolbag",
 src: "py",
 last: "20150130",
 desc: "The IDA Toolbag plugin provides many handy features, such as:\n* A 'History' view, that displays functions in the disassembly that you have decided are important, and the relationships between them.\n* A code path-searching tool, that lets you find what functions (or blocks) are forming a path between two locations.\n* Manage and run your IDC/Python scripts\n* Something that's also of considerable importance is that the IDA Toolbag lets you collaborate with other IDA users: one can publish his 'History', or import another user's history & even merge them!\n* See the official documentation for an extensive feature list."},

{name: "IDAtropy",
 url: "https://github.com/danigargu/IDAtropy",
 src: "py",
 last: "20210416",
 vers: "7.4",
 desc: "IDAtropy is a plugin for Hex-Ray's IDA Pro designed to generate charts of entropy and histograms using the power of idapython and matplotlib."},

{name: "IdaVSHelp",
 url: "https://github.com/andreafioraldi/IdaVSHelp",
 src: "py",
 cats: "dev, int",
 last: "20170513",
 vers: "6.8",
 desc: "IDAPython plugin to integrate Visual Studio Help Viewer in IDA Pro >= 6.8"},

{name: "idawasm",
 url: "https://github.com/fireeye/idawasm",
 src: "py",
 cats: "loader, proc",
 last: "20181004",
 vers: "7.1",
 desc: "These IDA Pro plugins add support for loading and disassembling WebAssembly modules.\n* control flow reconstruction and graph mode\n* code and data cross references\n* globals, function parameters, local variables, etc. can be renamed\n* auto-comment hint support"},

{name: "idax",
 url: "https://github.com/0xeb/idax",
 src: "c++",
 cats: "dev",
 last: "20211227",
 vers: "7.5",
 desc: "Xbox360/Xenon loader plugin for IDA 7.2+, supporting most known Xbox360/Xenon .XEX executable file formats."},

{name: "idaxex",
 url: "https://github.com/emoose/idaxex",
 src: "c++",
 cats: "loader",
 last: "20220218",
 vers: "7.5",
 desc: "Xbox360/Xenon loader plugin for IDA 7.2+, supporting most known Xbox360/Xenon .XEX executable file formats."},

{name: "IDA Xtensa",
 url: "https://github.com/themadinventor/ida-xtensa",
 src: "py",
 cats: "proc",
 last: "20190820",
 vers: "7.0",
 desc: "This is a processor plugin for IDA, to support the Xtensa core found in Espressif ESP8266. It does not support other configurations of the Xtensa architecture, but that is probably (hopefully) easy to implement."},

{name: "idb2pat",
 url: "https://github.com/alexander-pick/idb2pat",
 last: "20111008",
 desc: "IDB to Pat."},

{name: "idenLib",
 url: "https://github.com/secrary/IDA-scripts/tree/master/idenLib",
 src: "py",
 last: "20190226",
 desc: "Library Function Identification plugin for IDA Pro."},

{name: "IFL",
 url: "https://github.com/hasherezade/ida_ifl",
 src: "py",
 last: "20220120",
 vers: "7.0",
 desc: "Interactive Functions List is an user-friendly way to navigate between functions and their references."},

{name: "ifred",
 url: "https://github.com/Jinmo/ifred",
 last: "20220308",
 desc: "IDA command palette & further"},

{name: "ioctl_plugin",
 url: "https://github.com/sam-b/ioctl_plugin",
 last: "20180822",
 desc: "A tool to help when dealing with IOCTL codes and Windows driver IOCTL dispatch functions."},

{name: "IPyIDA",
 url: "https://github.com/eset/ipyida",
 src: "py",
 cats: "dev, int",
 last: "20220423",
 vers: "7.6",
 desc: "PyIDA is a python-only solution to use a IPython console in the context of IDA Pro. It spawns an IPython kernel that you can connect to with `ipython console --existing` in your shell or by opening a *QT Console* window in IDA Pro with `<Shift-.>`"},

{name: "JNIDA",
 url: "https://github.com/applicazza/JNIDA",
 src: "py",
 last: "20191118",
 vers: "7.4",
 desc: "Helps to rename JNI native methods and restore their C signatures"},

{name: "Kam1n0",
 url: "https://github.com/McGill-DMaS/Kam1n0-Plugin-IDA-Pro",
 last: "20220213",
 desc: "Kam1n0 is a scalable system that supports assembly code clone search. It allows a user to first index a (large) collection of binaries, and then search for the code clones of a given target function or binary file. Kam1n0 tries to solve the efficient subgraph search problem (i.e. graph isomorphism problem) for assembly functions."},

{name: "Karta",
 url: "https://github.com/CheckPointSW/Karta",
 last: "20220315",
 desc: "\"Karta\" (Russian for \"Map\") is a source code assisted fast binary matching plugin for IDA. Karta identifies and matches open-sourced libraries in a given binary using a unique technique that enables it to support huge binaries (> 200,000 functions) with almost no impact on the overall performance."},

{name: "Keypatch",
 url: "https://github.com/keystone-engine/keypatch",
 src: "py",
 last: "20210218",
 vers: "7.5",
 desc: "A multi-architeture assembler for IDA. Keypatch allows you enter assembly instructions to directly patch the binary under analysis. Powered by [Keystone engine](http://keystone-engine.org)."},

{name: "Labeless",
 url: "https://github.com/a1ext/labeless",
 src: "c++",
 cats: "debug",
 last: "20220325",
 vers: "6.95",
 desc: "Labeless is a plugin system for dynamic, seamless and realtime synchronization between IDA Database and Olly. Labels, function names and global variables synchronization is supported. \nLabeless provides easy to use dynamic dumping tool, which supports automatic on-the-fly imports fixing as well as convenient tool for IDA-Olly Python scripting synergy."},

{name: "LazyIDA",
 url: "https://github.com/L4ys/LazyIDA",
 last: "20220225",
 desc: "LazyIDA lets you perform many tasks simply and quickly (e.g., remove function return type in Hex-Rays, convert data into different formats, scan for format string vulnerabilities and a variety of shortcuts)"},

{name: "Lighthouse",
 url: "https://github.com/gaasedelen/lighthouse",
 src: "py",
 last: "20220217",
 vers: "7.0",
 desc: "Lighthouse is a Code Coverage Plugin for IDA Pro. The plugin leverages IDA as a platform to map, explore, and visualize externally collected code coverage data when symbols or source may not be available for a given binary."},

{name: "LoadProcConfig",
 url: "https://github.com/alexhude/LoadProcConfig",
 last: "20170921",
 desc: "LoadProcConfig is an IDA plugin to load processor configuration files."},

{name: "Localxrefs",
 url: "https://github.com/devttys0/ida/tree/master/plugins/localxrefs",
 last: "20210602",
 desc: "Finds references to any selected text from within the current function."},

{name: "Lucid",
 url: "https://github.com/gaasedelen/lucid",
 src: "py",
 cats: "decomp, dev",
 last: "20200915",
 vers: "7.2",
 desc: "Lucid is a developer-oriented IDA Pro plugin for exploring the Hex-Rays microcode. It was designed to provide a seamless, interactive experience for studying microcode transformations in the decompiler pipeline."},

{name: "Lumen",
 url: "https://github.com/naim94a/lumen",
 src: "rs",
 cats: "int",
 last: "20220121",
 vers: "7.2",
 desc: "A private Lumina server for IDA Pro written in Rust."},

{name: "MadNES",
 url: "https://github.com/patois/MadNES",
 src: "c++",
 cats: "int",
 last: "20120912",
 vers: "4.9",
 desc: "This plugin exports IDA names to FCEUXD SP symbols. These can be loaded by FCEUXD SP to allow symbolic debugging."},

{name: "MazeWalker",
 url: "https://github.com/0xPhoeniX/MazeWalker",
 src: "py",
 cats: "trace",
 last: "20220116",
 desc: "Toolkit for enriching and speeding up static malware analysis. MazeWalker’s goal is to reduce malware analysis time by automating runtime data collection and better visualization eventually helping a researcher to concentrate on static analysis and less on its dynamic part."},

{name: "MC68K Processor Model Extension",
 url: "https://github.com/LucienMP/idapro_m68k",
 last: "20190714",
 desc: "This is a sample plugin for extending gdb support for step-over for the M68K, and to enable type information support so you can press \"y\" on functions and have the parameters propagate inside and back out of the function."},

{name: "MicroAVX",
 url: "https://github.com/gaasedelen/microavx",
 src: "py",
 cats: "decomp",
 last: "20200722",
 vers: "7.5",
 desc: "An AVX Lifter for the Hex-Rays Decompiler. It adds partial support for a number of common instructions from Intel's Advanced Vector Extensions (AVX). This plugin demonstrates how the Hex-Rays microcode can be used to lift and decompile new or previously unsupported instructions."},

{name: "mipslocalvars",
 url: "https://github.com/devttys0/ida/tree/master/plugins/mipslocalvars",
 last: "20210602",
 desc: "Names stack variables used by the compiler for storing registers on the stack, simplifying stack data analysis (MIPS only)"},

{name: "mipsrop",
 url: "https://github.com/devttys0/ida/tree/master/plugins/mipsrop",
 last: "20210602",
 desc: "* Allows you to search for suitable ROP gadgets in MIPS executable code\n* Built-in methods to search for common ROP gadgets"},

{name: "mkYARA IDA Plugin",
 url: "https://github.com/fox-it/mkYARA",
 src: "py",
 last: "20191216",
 vers: "7.4",
 desc: "IDA plugin to easily create YARA signatures with mkYARA."},

{name: "MrsPicky",
 url: "https://github.com/patois/mrspicky",
 src: "py",
 cats: "decomp",
 last: "20191218",
 vers: "7.3",
 desc: "An IDAPython decompiler script that helps auditing calls to the memcpy() and memmove() functions."},

{name: "MSDN Helper",
 url: "https://github.com/Z-Rantom/IMH",
 last: "20160905",
 desc: "This tool will help you to get to Offline MSDN help while using IDA Pro."},

{name: "MyNav",
 url: "https://code.google.com/p/mynav/",
 src: "c++",
 last: "20100903",
 vers: "5.6",
 desc: "MyNav is a plugin for IDA Pro to help reverse engineers in the most typical task like discovering what functions are responsible of some specifical tasks, finding paths between \"interesting\" functions and data entry points."},

{name: "nao",
 url: "https://github.com/tkmru/nao",
 src: "py",
 last: "20210505",
 desc: "nao (no-meaning assembly omitter) is dead code eliminator plugin for IDA pro."},

{name: "NDSLdr",
 url: "https://github.com/patois/NDSLdr",
 src: "c++",
 cats: "loader",
 last: "20170205",
 vers: "5.0",
 desc: "Nintendo DS ROM loader module for IDA Pro."},

{name: "NECromancer",
 url: "https://github.com/patois/NECromancer",
 src: "py",
 cats: "proc",
 last: "20180508",
 vers: "7.0",
 desc: "IDA Pro V850 Processor Module Extension."},

{name: "nesdbg",
 url: "https://github.com/patois/nesdbg",
 src: "c++",
 cats: "debug",
 last: "20181218",
 vers: "4.9",
 desc: "Failed attempt in creating an IDA Pro debugger plugin for NES ROMs"},

{name: "NES Loader",
 url: "https://github.com/patois/nesldr",
 src: "c++",
 cats: "loader",
 last: "20200226",
 vers: "4.9",
 desc: "Nintendo Entertainment System (NES) ROM loader module for IDA Pro."},

{name: "NES Loader (py)",
 url: "https://github.com/Jinmo/nesldr-py",
 src: "py",
 cats: "loader",
 last: "20210715",
 vers: "7.0",
 desc: "Nintendo Entertainment System (NES) ROM loader module for IDA Pro (Python port for IDA 7.x)."},

{name: "NIOS2",
 url: "https://github.com/ptresearch/nios2",
 src: "py",
 cats: "loader",
 last: "20180924",
 desc: "An IDA Pro processor module for Altera Nios II Classic/Gen2 microprocessor architecture."},

{name: "nmips",
 url: "https://github.com/0rganizers/nmips",
 src: "py",
 cats: "debug, loader, proc",
 last: "20210915",
 desc: "IDA plugin to enable nanoMIPS processor support. This is not limited to simple disassembly, but fully supports decompilation and even fixes up the stack in certain functions using custom microcode optimizers. It also supports relocations and automatic ELF detection (even though the UI might not show it, it kinda works). Debugging also works thanks to GDB and it also does some other stuff, such as automatic switch detections."},

{name: "NSIS Reversing Suite",
 url: "https://github.com/isra17/nrs/",
 src: "py",
 cats: "loader",
 last: "20180519",
 desc: "NRS is a set of Python libraries used to unpack and analysis NSIS installer's data. It also feature an IDA plugin used to disassembly the NSIS Script of an installer."},

{name: "obfDetect",
 url: "https://github.com/mcdulltii/obfDetect",
 src: "py",
 cats: "deobf",
 last: "20220320",
 vers: "7.4",
 desc: "A plugin to automatically detect obfuscated code and state machines in binaries."},

{name: "Optimice",
 url: "https://code.google.com/p/optimice/",
 src: "py",
 cats: "deobf",
 last: "20120805",
 vers: "6.0",
 desc: "This plugin enables you to remove some common obfuscations and rewrite code to a new segment. Currently supported optimizations are: Dead code removal, JMP merging, JCC opaque predicate removal, Pattern based deobfuscations"},

{name: "Oregami",
 url: "https://github.com/shemesh999/oregami",
 src: "py",
 last: "20200406",
 desc: "A plugin analyzing the current function to find the usage frame of registers. Oregami eases the work when tracking the use of a register within a function, by limiting the search to occurrences related to the one currently highlighted instead of the whole function. It also allows localized renaming of the registers, and batch type giving to multiple opcodes using the registers."},

{name: "Patching",
 url: "https://github.com/gaasedelen/patching",
 src: "py",
 last: "20220210",
 vers: "7.6",
 desc: "Interactive Binary Patching for IDA Pro. This project extends the popular IDA Pro disassembler to create a more robust interactive binary patching workflow designed for rapid iteration."},

{name: "Plus22",
 url: "https://github.com/v0s/plus22",
 last: "20150111",
 desc: "Plus22 transforms x86_64 executables to be processed with 32-bit version of Hex-Rays Decompiler."},

{name: "Plympton",
 url: "https://github.com/rogwfu/plympton",
 src: "py",
 cats: "int",
 last: "20141125",
 desc: "A gem to read program disassembly from a YAML dump. The YAML dump is generated from an IDA Pro python script. This script is included along with this Gem (func.py)"},

{name: "Pomidor",
 url: "https://github.com/iphelix/ida-pomidor",
 src: "py",
 last: "20140923",
 desc: "IDA Pomidor is a plugin for Hex-Ray's IDA Pro disassembler that will help you retain concentration and productivity during long reversing sessions by encouraging you to take breaks."},

{name: "Ponce",
 url: "https://github.com/illera88/Ponce",
 src: "c++",
 last: "20220421",
 vers: "7.6",
 desc: "Taint analysis and symbolic execution over binaries in an easy and intuitive fashion."},

{name: "Prefix",
 url: "https://github.com/gaasedelen/prefix",
 src: "py",
 last: "20200424",
 vers: "7.4",
 desc: "Prefix is a small function prefixing plugin for IDA Pro. The plugin augments IDA's function renaming capabilities by adding a handful of convenient prefixing actions to relevant right click menus."},

{name: "Processor changer",
 url: "https://github.com/techbliss/Processor-Changer",
 last: "20140811",
 desc: "Change processor without restarting IDA."},

{name: "PSIDA",
 url: "https://github.com/soggysec/psida",
 src: "py",
 cats: "collab",
 last: "20180803",
 vers: "7.0",
 desc: "PSIDA is a collection of useful Python scripts for IDA. At this point, PSIDA focuses on collaborative reverse engineering in two models."},

{name: "pwndbg",
 url: "https://github.com/pwndbg/pwndbg",
 src: "py",
 cats: "debug, int",
 last: "20220421",
 vers: "7.0",
 desc: "GDB plug-in that makes debugging with GDB suck less, with a focus on features needed by low-level software developers, hardware hackers, reverse-engineers and exploit developers. NOTE: IDA integration through small XMLRPC server."},

{name: "pyhexraysdeob",
 url: "https://github.com/idapython/pyhexraysdeob",
 src: "py",
 cats: "deobf",
 last: "20191015",
 desc: "A port of Rolf Rolles' HexRaysDeob to Python."},

{name: "Python Editor",
 url: "https://github.com/techbliss/Python_editor",
 last: "20201225",
 desc: "Python editor based IDA Pro. The plugin helps python devs with scripting and running python scripts, and creating them. IT have many functions, code recognition and more."},

{name: "python-idb",
 url: "https://github.com/williballenthin/python-idb",
 src: "py",
 cats: "dev",
 last: "20210806",
 vers: "7.6",
 desc: "not an IDA Pro plugin but allows to open IDA databases (`*.idb` and `*.i64`) and run a simple subset of IDAPython API on top of them, without the IDA Pro itself."},

{name: "qb-sync",
 url: "https://github.com/quarkslab/qb-sync",
 src: "py",
 cats: "int",
 last: "20150713",
 desc: "qb-sync is an open source tool to add some helpful glue between IDA Pro and Windbg. Its core feature is to dynamically synchronize IDA's graph windows with Windbg's position."},

{name: "QScripts",
 url: "https://github.com/0xeb/ida-qscripts",
 src: "c++",
 cats: "dev",
 last: "20220420",
 vers: "7.7",
 desc: "An IDA scripting productivity plugin. With this plugin, you will be able to easily write and test scripts using your favorite editor. `ida-qscripts` will automatically detect changes to your script or one of its dependencies and automatically reload them and re-execute your script."},

{name: "Qualcomm Loader",
 url: "https://github.com/daxgr/qcom-mbn-ida-loader",
 src: "c++",
 cats: "loader",
 last: "20140123",
 desc: "IDA loader plugin for Qualcomm Bootloader Stages"},

{name: "Recompiler",
 url: "https://github.com/bastkerg/Recomp",
 src: "py",
 last: "20141208",
 desc: "IDA recompiler, no docs no help."},

{name: "RECON2017",
 url: "https://github.com/tmr232/RECon2017",
 src: "py",
 cats: "ui",
 last: "20170616",
 vers: "6.8",
 desc: "RECON 2017 IDA skin & color scheme"},

{name: "Reef",
 url: "https://github.com/darx0r/Reef",
 src: "py",
 last: "20160714",
 vers: "6.8",
 desc: "IDAPython plugin for finding Xrefs from a function."},

{name: "REmatch",
 url: "https://github.com/nirizr/rematch",
 src: "py",
 cats: "int",
 last: "20181128",
 desc: "REmatch, a complete binary diffing framework that works by revealing and identifying previously reverse engineered similar functions and migrating documentation and annotations to current IDB."},

{name: "REobjc",
 url: "https://github.com/duo-labs/idapython",
 src: "py",
 last: "20180426",
 desc: "REobjc is an IDAPython module designed to make proper cross references between calling functions and called functions in Objective-C methods. The current form of the module supports X64, and will be updated to also support ARM in the future."},

{name: "REProgram",
 url: "https://github.com/jkoppel/REProgram",
 src: "c++",
 last: "20111227",
 vers: "6.1",
 desc: "A way of making almost-arbitrary changes to an executable when run under a debugger -- even changes that don't fit."},

{name: "retdec",
 url: "https://github.com/avast/retdec-idaplugin",
 src: "c++",
 cats: "decomp",
 last: "20200818",
 vers: "7.5",
 desc: "IDA plugin for retdec - a retargetable machine-code decompiler based on LLVM."},

{name: "ret-sync",
 url: "https://github.com/bootleg/ret-sync",
 src: "py",
 cats: "debug, int",
 last: "20220213",
 vers: "7.4",
 desc: "ret-sync stands for Reverse-Engineering Tools synchronization. It's a set of plugins that help to synchronize a debugging session (WinDbg/GDB/LLDB/OllyDbg2/x64dbg) with IDA disassembler. The underlying idea is simple: take the best from both worlds (static and dynamic analysis)."},

{name: "REtypedef",
 url: "https://github.com/zyantific/REtypedef",
 last: "20150103",
 desc: "REtypedef is an IDA PRO plugin that allows defining custom substitutions for function names. It comes with a default ruleset providing substitutions for many common STL types."},

{name: "rizzo",
 url: "https://github.com/devttys0/ida/tree/master/plugins/rizzo",
 src: "py",
 last: "20210602",
 vers: "7.4",
 desc: "Identifies and re-names functions between two or more IDBs based on:\n* Formal signatures (i.e., exact function signatures)\n* References to unique string\n* References to unique constants\n* Fuzzy signatures (i.e., similar function signatures)\n* Call graphs (e.g., identification by association)"},

{name: "Samsung S4 Rom Loader",
 url: "https://github.com/cycad/mbn_loader",
 desc: "IDA Pro Loader Plugin for Samsung Galaxy S4 ROMs"},

{name: "Sark",
 url: "https://github.com/tmr232/Sark/",
 src: "py",
 cats: "dev",
 last: "20220318",
 vers: "7.4",
 desc: "Sark, (named after the notorious Tron villain,) is an object-oriented scripting layer written on top of IDAPython. Sark is easy to use and provides tools for writing advanced scripts and plugins."},

{name: "ScratchABit",
 url: "https://github.com/pfalcon/ScratchABit",
 last: "20201125",
 desc: "ScratchABit is an interactive incremental disassembler with data/control flow analysis capabilities. ScratchABit is dedicated to the efforts of the OpenSource reverse engineering community (reverse engineering to produce OpenSource drivers/firmware for hardware not properly supported by vendors)."},

{name: "Screen recorder",
 url: "https://github.com/techbliss/Ida_Pro_Screen_Recorder",
 last: "20160727",
 desc: "IDA Pro Qt Plugin for recording reversing sessions."},

{name: "Sega Genesis/Megadrive Tools 2",
 url: "https://github.com/lab313ru/smd_ida_tools2",
 src: "c++",
 cats: "loader, debug",
 last: "20210625",
 vers: "7.5",
 desc: "Special IDA Pro tools for the Sega Genesis/Megadrive romhackers. Updated to at least IDA 7.5"},

{name: "Sig Maker",
 url: "https://github.com/ajkhoury/SigMaker-x64",
 src: "c++",
 last: "20210728",
 vers: "7.0",
 desc: "Can create sigs automatically and has a wide variety of functions."},

{name: "SigMakerEx",
 url: "https://github.com/kweatherman/sigmakerex",
 src: "c++",
 last: "20220216",
 vers: "7.6",
 desc: "Enhanced IDA Pro signature generator plugin."},

{name: "SimplifyGraph",
 url: "https://github.com/fireeye/SimplifyGraph",
 src: "c++",
 last: "20180129",
 vers: "6.95",
 desc: "An IDA Pro plugin to assist with complex graphs."},

{name: "Simulator",
 url: "https://github.com/nihilus/IDASimulator",
 src: "py",
 cats: "debug",
 last: "20140902",
 vers: "6.4",
 desc: "IDASimulator is a plugin that extends IDA's conditional breakpoint support, making it easy to augment / replace complex executable code inside a debugged process with Python code."},

{name: "Snippet Detector",
 url: "https://github.com/zaironne/SnippetDetector",
 src: "py",
 last: "20150424",
 vers: "6.7",
 desc: "Snippet Detector is an IDA Python scripts project used to detect snippets from 32bit disassembled files. snippet is the word used to identify a generic sequence of instructions (at the moment a snippet is indeed a defined function). The aim of the tool is to collect many disassembled snippets inside a database for the detection process."},

{name: "Snowman Decompiler",
 url: "https://github.com/yegord/snowman",
 src: "c++",
 cats: "decomp",
 last: "20210621",
 desc: "Snowman is a native code to C/C++ decompiler. Standalone and IDA Plugin. [Source Code](https://github.com/yegord/snowman)"},

{name: "Splode",
 url: "https://github.com/zachriggle/ida-splode",
 src: "c++",
 last: "20141010",
 desc: "Augmenting Static Reverse Engineering with Dynamic Analysis and Instrumentation"},

{name: "spu3dbg",
 url: "https://github.com/revel8n/spu3dbg",
 src: "c++",
 cats: "debug",
 last: "20160328",
 desc: "Ida Pro debugger module for the anergistic SPU emulator."},

{name: "Stadeo",
 url: "https://github.com/eset/stadeo",
 src: "py",
 cats: "deobf",
 last: "20211108",
 desc: "Stadeo is a set of tools primarily developed to facilitate analysis of Stantinko, which is a botnet performing click fraud, ad injection, social network fraud, password stealing attacks and cryptomining, using IDA."},

{name: "Stingray",
 url: "https://github.com/darx0r/Stingray",
 src: "py",
 last: "20210319",
 vers: "7.2",
 desc: "Stingray is an IDAPython plugin for finding function strings. The search is from the current position onwards in the current function. It can do it recursively also with configurable search depth. The results order is the natural order of strings in the BFS search graph."},

{name: "Structure Dump",
 url: "http://www.openrce.org/downloads/details/227/Structure_Dump",
 src: "c++",
 last: "20070405",
 desc: "StructDump is an IDA plugin, allowing you to export IDA types into high-level language definitions. Currently, C++ is supported."},

{name: "Styler",
 url: "https://github.com/techbliss/IDA-Styler",
 src: "py",
 cats: "ui",
 last: "20140725",
 vers: "6.5",
 desc: "Small Plugin to change the style of Ida Pro."},

{name: "syms2elf",
 url: "https://github.com/danigargu/syms2elf",
 src: "py",
 last: "20211117",
 vers: "7.5",
 desc: "A plugin for IDA Pro and radare2 to export the symbols recognized to the ELF symbol table."},

{name: "SyncReven",
 url: "https://github.com/riskeco/SyncReven",
 src: "py",
 cats: "int",
 last: "20210915",
 vers: "7.3",
 desc: "Reven integration plugin: synchronize the Axion current analysis window with some code opened in IDA."},

{name: "Synergy",
 url: "https://github.com/CubicaLabs/IDASynergy",
 src: "py",
 cats: "collab",
 last: "20150128",
 desc: "A combination of an IDAPython Plugin and a control version system that result in a new reverse engineering collaborative addon for IDA Pro. By http://cubicalabs.com/"},

{name: "Tarkus",
 url: "https://github.com/tmr232/Tarkus",
 src: "py",
 last: "20150813",
 vers: "6.7",
 desc: "Tarkus is a plugin manager for IDA Pro, modelled after Python's pip."},

{name: "TurboDiff",
 url: "http://www.coresecurity.com/corelabs-research/open-source-tools/turbodiff",
 src: "c++",
 last: "20111213",
 vers: "5.1",
 desc: "Turbodiff is a binary diffing tool developed as an IDA plugin. It discovers and analyzes differences between the functions of two binaries."},

{name: "UEFI_RETool",
 url: "https://github.com/yeggor/UEFI_RETool/tree/master/ida_plugin",
 last: "20210803",
 desc: "IDA Plugin for UEFI firmware executable images analysing"},

{name: "uEmu",
 url: "https://github.com/alexhude/uEmu",
 src: "py",
 last: "20211013",
 vers: "7.2",
 desc: "uEmu is a tiny cute emulator plugin for IDA based on unicorn engine. Supports following architectures out of the box: x86, x64, ARM, ARM64, MIPS, MIPS64"},

{name: "Virtuailor",
 url: "https://github.com/0xgalz/Virtuailor",
 src: "py",
 last: "20200606",
 vers: "7.4",
 desc: "Virtuailor is an IDAPython tool that reconstructs vtables for C++ code written for intel architechture and both 32bit and 64bit code."},

{name: "VirusBattle",
 url: "https://github.com/axmat/virusbattle-ida-plugin",
 src: "py",
 cats: "int",
 last: "20150526",
 desc: "The plugin is an integration of Virus Battle API to the well known IDA Disassembler. Virusbattle is a web service that analyses malware and other binaries with a variety of advanced static and dynamic analyses."},

{name: "VMAttack",
 url: "https://github.com/anatolikalysch/VMAttack",
 src: "py",
 cats: "deobf",
 last: "20171130",
 vers: "6.9",
 desc: "Static and dynamic virtualization-based packed analysis and deobfuscation."},

{name: "VT-IDA Plugin",
 url: "https://github.com/VirusTotal/vt-ida-plugin",
 src: "py",
 cats: "int",
 last: "20201005",
 desc: "This is the official VirusTotal plugin for Hex-Rays IDA Pro. This plugin integrates functionality from VirusTotal web services into the IDA Pro's user interface."},

{name: "Win32 LST to Inline Assembly",
 url: "https://github.com/binrapt/ida",
 src: "py",
 last: "20090710",
 desc: "Python script which extracts procedures from IDA Win32 LST files and converts them to correctly dynamically linked compilable Visual C++ inline assembly."},

{name: "WinIOCtlDecoder",
 url: "https://github.com/tandasat/WinIoCtlDecoder",
 src: "py",
 last: "20150602",
 desc: "An IDA Pro plugin which decodes a Windows Device I/O control code into DeviceType, FunctionCode, AccessType and MethodType."},

{name: "X86Emu",
 url: "http://www.idabook.com/ida-x86emu/",
 desc: "Its purpose is to allow a reverse engineer the chance to step through x86 code while reverse engineering a binary.  The plugin can help you step through any x86 binary from any platform. For Windows binaries, many common library calls are trapped and emulated by the emulator, allowing for a higher fidelity emulation. I find it particularly useful for stepping through obfuscated code as it automatically reorganizes an IDA disassembly based on actual code paths."},

{name: "xdeobf",
 url: "https://github.com/teapotd/xdeobf",
 src: "c++",
 cats: "deobf",
 last: "20200324",
 vers: "7.2",
 desc: "Experimental deobfuscation plugin for IDA 7.2. It aims to reverse control flow flattening transformation that I encountered (probably a variation of obfuscator-llvm)."},

{name: "Xex Loader for IDA 6.6",
 url: "http://xorloser.com/blog/?p=395",
 cats: "loader",
 last: "20130923",
 vers: "6.6",
 desc: "This adds the ability to load xex files into IDA directly without having to first process them in any way. It processes the xex file as much as possible while loading to minimise the work required by the user to get it to a state fit for reversing."},

{name: "xray",
 url: "https://github.com/patois/xray",
 src: "py",
 cats: "decomp, ui",
 last: "20220129",
 vers: "7.4",
 desc: "Hexrays decompiler plugin that colorizes and filters the decompiler's output based on regular expressions"},

{name: "YaCo",
 url: "https://github.com/DGA-MI-SSI/YaCo",
 src: "py",
 cats: "collab",
 last: "20181114",
 vers: "7.1",
 desc: "Collaborative Reverse-Engineering for IDA. When enabled, an unlimited number of users can work simultaneously on the same binary. Any modification done by any user is synchronized through git version control. It has been initially released at [SSTIC 2017](https://www.sstic.org/2017/presentation/YaCo/)"},

{name: "Yagi",
 url: "https://github.com/airbus-cert/Yagi",
 src: "c++",
 cats: "decomp, int",
 last: "20211220",
 vers: "7.6",
 desc: "Yet Another Ghidra Integration for IDA. Yagi intends to include the wonderful Ghidra decompiler into both IDA pro and IDA Free."},

];
